name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      src_changed: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@v7
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            src:
              - '**'
              - '!**.md'
              - '!docs/**'
              - '!LICENSE'
              - '!.gitignore'

  actionlint:
    needs: changes
    if: needs.changes.outputs.src_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
  lint:
    needs: changes
    if: needs.changes.outputs.src_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm run format -- --check

  test:
    needs: changes
    if: needs.changes.outputs.src_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
      - run: npm ci
      - run: npm run test

  build:
    needs: changes
    if: needs.changes.outputs.src_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
      - run: npm ci
      - run: npm run build

  e2e:
    needs: changes
    if: needs.changes.outputs.src_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npx playwright install --with-deps
      - run: npm run test:e2e
